version: "3.7"
services:
  postgres:
    image: postgres:15
    container_name: psql
    env_file: .env
    networks:
      - odoo_network

  odoo:
    image: odoo:16
    container_name: odoo
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "8069:8069"
    volumes:
      - ./etc:/etc/odoo
      - ./scripts:/scripts
    entrypoint: >
      bash -c "
      echo 'Running module update script...'; 
      /scripts/python3 /scripts/update_module_list.py;
      echo 'Module update script completed!'"
    networks:
      - odoo_network

volumes:
  pgdata:

networks:
  odoo_network:
