name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Debug repository files
      - name: List repository files
        run: ls -la

      # Step 3: Verify required directories and files
      - name: Verify addons and config files
        run: |
          test -d ./addons || { echo "Addons directory not found"; exit 1; }
          test -f ./etc/odoo.conf || { echo "odoo.conf file not found"; exit 1; }
          echo "Addons and config files verified"

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/odoo16-custom:latest

      # Step 10: Verify addons in the Docker image
      - name: Debug addons in Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/odoo16-custom:latest
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/odoo16-custom:latest ls -la /mnt/extra-addons

      # Step 11: Verify the image (optional)
      - name: Run Docker image for verification
        run: |
          docker run --rm -d -p 8069:8069 \
            -v /home/oddoc/odoo/pgdata:/var/lib/postgresql/data/pgdata \
            -v /home/oddoc/odoo/odoo_data:/var/lib/odoo \
            ${{ secrets.DOCKER_USERNAME }}/odoo16-custom:latest