name: Odoo CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Odoo Application
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          # POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose


    - name: Set up Docker Compose
      run: |
        docker-compose up -d postgres
        sleep 10  # Ensure PostgreSQL is ready

    - name: Run Odoo Tests
      run: |
        docker-compose up -d odoo
        sleep 10  # Wait for Odoo to start
        docker exec odoo /scripts/test.sh
        docker-compose down

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Odoo Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/odoo:16 .
        docker push ${{ secrets.DOCKER_USERNAME }}/odoo:16
