name: Odoo CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Odoo Application
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Debug repository files
    - name: List repository files
      run: ls -la

    # Verify addons directory exists
    - name: Verify addons directory
      run: ls -la ./addons || echo "addons directory not found"

    # Verify odoo.conf file exists
    - name: Verify odoo.conf file
      run: ls -la ./etc/odoo.conf || echo "odoo.conf file not found"

    # Copy addons and config to docker folder (if necessary)
    - name: Copy addons and odoo.conf to docker folder
      run: |
        mkdir -p docker/addons
        mkdir -p docker/etc
        cp -r ./addons/* ./docker/addons/
        cp ./etc/odoo.conf ./docker/etc/odoo.conf

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Set up Docker Compose
    - name: Set up Docker Compose
      run: |
        docker-compose up -d postgres
        sleep 10  # Ensure PostgreSQL is ready

    - name: Initialize Odoo Database
      run: |
        docker-compose run --rm odoo odoo -i base --db_host=${HOST} --db_port=5432 --db_user=${USER} --db_password=${PASSWORD} --db_name=${POSTGRES_DB}


    # Run the update_module_list.py script
    - name: Run update_module_list.py
      run: |
        docker-compose run --rm odoo python3 /scripts/update_module_list.py

    # Run Odoo Tests
    - name: Run Odoo Tests
      run: |
        docker-compose up -d odoo
        sleep 10  # Wait for Odoo to start
        # Run tests if applicable
        # docker-compose exec odoo /scripts/test.sh
        docker-compose down

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Odoo Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/odoo:16 .
        docker push ${{ secrets.DOCKER_USERNAME }}/odoo:16
